# Generated by Django 5.0.6 on 2024-06-16 01:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id_cliente', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nm_cliente', models.CharField(max_length=100)),
                ('cpf_cnpj', models.CharField(max_length=22)),
                ('cep', models.CharField(blank=True, max_length=11, null=True)),
                ('data_abertura', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=18, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=150, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('tipo_cliente', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id_empresa', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_fantasia', models.CharField(max_length=150)),
                ('razao_social', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=22)),
                ('status', models.CharField(max_length=30, null=True)),
                ('cnae_principal_descricao', models.CharField(blank=True, max_length=150, null=True)),
                ('cnae_principal_codigo', models.IntegerField(blank=True, null=True)),
                ('cep', models.CharField(blank=True, max_length=11, null=True)),
                ('data_abertura', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=18, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=150, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='movimento',
            fields=[
                ('dt_lancamento', models.DateField(auto_now_add=True)),
                ('horario', models.TimeField(auto_now_add=True)),
                ('dt_caixa', models.DateField(auto_now_add=True)),
                ('id_movimento', models.IntegerField(default=0)),
                ('nm_tp_movimento', models.CharField(max_length=100)),
                ('id_cliente', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nm_cliente', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=300)),
                ('status', models.IntegerField(default=0)),
                ('vr_movimento', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_movimento',
            fields=[
                ('id_tp_movimento', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nm_tp_movimento', models.CharField(max_length=100)),
            ],
        ),
    ]
