# Generated by Django 5.0.6 on 2024-06-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcaixa', '0002_folhapgto'),
    ]

    operations = [
        migrations.AddField(
            model_name='folhapgto',
            name='id_folha',
            field=models.AutoField(default=0, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='folhapgto',
            name='id_cliente',
            field=models.IntegerField(default=0),
        ),
    ]
