# Generated by Django 5.0.6 on 2024-06-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcaixa', '0005_movimento_id_alter_movimento_id_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimento',
            name='id',
        ),
        migrations.AlterField(
            model_name='movimento',
            name='id_cliente',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='movimento',
            name='id_movimento',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
