# Generated by Django 5.0.6 on 2024-06-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcaixa', '0006_remove_movimento_id_alter_movimento_id_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='id_cliente',
            field=models.IntegerField(default=0),
        ),
    ]
