# Generated by Django 5.0.6 on 2024-06-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcaixa', '0007_alter_movimento_id_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='id_usuario',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='nm_usuario',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='folhapgto',
            name='id_usuario',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='folhapgto',
            name='nm_usuario',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='movimento',
            name='id_usuario',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='movimento',
            name='nm_usuario',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
