# Generated by Django 5.0.6 on 2024-06-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcaixa', '0008_clientes_id_usuario_clientes_nm_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cpf_cnpj',
            field=models.CharField(max_length=22),
        ),
    ]
