# Generated by Django 5.0.6 on 2024-06-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcaixa', '0009_alter_clientes_cpf_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cpf_cnpj',
            field=models.CharField(max_length=22),
        ),
    ]
