# Generated by Django 5.0.6 on 2024-06-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcaixa', '0010_alter_clientes_cpf_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='folhapgto',
            name='cod_pe',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
