# Generated by Django 5.0.6 on 2024-06-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcaixa', '0011_folhapgto_cod_pe'),
    ]

    operations = [
        migrations.AddField(
            model_name='folhapgto',
            name='valor_b',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
