# Generated by Django 5.0.6 on 2024-06-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcaixa', '0012_folhapgto_valor_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folhapgto',
            name='nm_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
