# Generated by Django 5.0.6 on 2024-07-05 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcaixa', '0015_alter_folhapgto_cod_pe'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimento',
            name='vr_entrada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
