# Generated by Django 5.0.6 on 2024-07-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcaixa', '0016_movimento_vr_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimento',
            name='cod_forma_entrada',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='movimento',
            name='cod_forma_parcelado',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='movimento',
            name='vr_parcelado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
