# Generated by Django 5.0.6 on 2024-07-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcaixa', '0017_movimento_cod_forma_entrada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bancos',
            fields=[
                ('id_banco', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='forma_pgtos',
            fields=[
                ('id_forma_pgtos', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='clientes',
            name='dt_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
