# Generated by Django 5.0.6 on 2024-07-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcaixa', '0018_bancos_forma_pgtos_clientes_dt_atualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='bancos',
            name='dt_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='folhapgto',
            name='dt_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='forma_pgtos',
            name='dt_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='movimento',
            name='dt_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
