# Generated by Django 5.0.6 on 2024-07-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcaixa', '0019_bancos_dt_atualizacao_folhapgto_dt_atualizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folhapgto',
            name='id_instrutor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='folhapgto',
            name='nm_instrutor',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
