# Generated by Django 5.0.6 on 2024-07-11 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcaixa', '0023_alter_folhapgto_cod_pe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folhapgto',
            name='cod_pe',
        ),
    ]
