# Generated by Django 5.0.6 on 2024-07-14 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcaixa', '0026_folhapgto_nm_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimento',
            name='ACC',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='movimento',
            name='Categoria_A',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='movimento',
            name='Categoria_B',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='movimento',
            name='Categoria_C',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='movimento',
            name='Categoria_D',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='movimento',
            name='codigo_pe',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movimento',
            name='data_pgto',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='movimento',
            name='dt_atualizacao_folhapgto',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='movimento',
            name='forma_pgto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='movimento',
            name='idforma_pgtos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movimento',
            name='idinstrutor_catA',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movimento',
            name='idinstrutor_catB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movimento',
            name='idmovimento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movimento',
            name='idusuario_folhapgto',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='movimento',
            name='nm_categoria',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='movimento',
            name='nm_instrutor_catA',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='movimento',
            name='nm_instrutor_catB',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='movimento',
            name='nm_usuario_folhapgto',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='movimento',
            name='status_pgto_a',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='movimento',
            name='status_pgto_b',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='movimento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='movimento',
            name='valor_b',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='movimento',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
