# Generated by Django 5.0.6 on 2024-07-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcaixa', '0027_movimento_acc_movimento_categoria_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='nm_instrutor_catA',
            field=models.CharField(default=0, max_length=150),
        ),
        migrations.AlterField(
            model_name='movimento',
            name='nm_instrutor_catB',
            field=models.CharField(default=0, max_length=150),
        ),
    ]
