# Generated by Django 5.0.6 on 2024-07-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcaixa', '0028_alter_movimento_nm_instrutor_cata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='nm_instrutor_catA',
            field=models.CharField(default=0, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='movimento',
            name='nm_instrutor_catB',
            field=models.CharField(default=0, max_length=150, null=True),
        ),
    ]
