# Generated by Django 5.0.6 on 2024-07-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcaixa', '0029_alter_movimento_nm_instrutor_cata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='habilitacoes',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('id_cliente', models.IntegerField(default=0)),
                ('cod_pe', models.CharField(default=0, max_length=50, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dt_cadastro', models.DateField(auto_now_add=True)),
                ('hora_cadastro', models.TimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('id_usuario', models.IntegerField(default=0)),
            ],
        ),
    ]
