# Generated by Django 5.0.6 on 2024-07-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcaixa', '0030_habilitacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimento',
            name='dt_pgto',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='movimento',
            name='hora_pgto',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='movimento',
            name='id_habilitacoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movimento',
            name='tem_na_folha',
            field=models.BooleanField(default=False),
        ),
    ]
